version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - TZ=Africa/Lagos
  frontend:
    image: node:18
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    command: >
      /bin/sh -c "cd /app/frontend && npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "3000:3000"
